import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./contexts/UserContext";
import { JSX, ReactNode } from "react";

export const metadata: Metadata = {
  title: "Foodify",
  description: "Generated by Pum2A",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
  pageProps: JSX.IntrinsicAttributes & { children: ReactNode }
) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <UserProvider {...pageProps}>{children}</UserProvider>
      </body>
    </html>
  );
}
